// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0GimEfZ__6rrs1zukk_zLp0KvnnesgHU',
    appId: '1:182126563583:web:bf9b0dc02bbc596f05bcca',
    messagingSenderId: '182126563583',
    projectId: 'food-delivery-5498f',
    authDomain: 'food-delivery-5498f.firebaseapp.com',
    storageBucket: 'food-delivery-5498f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvCffOALvUAnO1-gSxKT1PatdTKe4hYU',
    appId: '1:182126563583:android:a58bd6e8abc1394305bcca',
    messagingSenderId: '182126563583',
    projectId: 'food-delivery-5498f',
    storageBucket: 'food-delivery-5498f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWesKE4Tc4h4iuqjICDkwe00LTsSilLjc',
    appId: '1:182126563583:ios:d62c6ea471033af505bcca',
    messagingSenderId: '182126563583',
    projectId: 'food-delivery-5498f',
    storageBucket: 'food-delivery-5498f.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWesKE4Tc4h4iuqjICDkwe00LTsSilLjc',
    appId: '1:182126563583:ios:1fe43b93a728e73005bcca',
    messagingSenderId: '182126563583',
    projectId: 'food-delivery-5498f',
    storageBucket: 'food-delivery-5498f.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
